language: python
python:
  - "2.7.13"

sudo: false
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev


env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'

  - secure: axBDnKRsoWFK+yYseiC2VZ76aiKjRnT25p4R7wtMs0UXhydbJvac1lWEUWVm8XwiMKNK+sor3csVlm6mfuAqEAtBtC6mprS4oFgFdUSPoA0pPus99GLkOXJw6AD00R1p3O5S6ukQ1JNhMJZvIRhKFm+icd8+VJkn8GGclnuqrp4=
  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS=1 ODOO_REPO="odoo/odoo"
  - TESTS=1 ODOO_REPO="OCA/OCB"

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install unicodecsv unidecode ofxparse
  - pip install git+https://github.com/akretion/factur-x
  - pip install python-stdnum
  - pip install pypdf2

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success

